### ISSUE TITLE
5xx responses from API should raise a TransientError

### ISSUE THREAD

**Issue by sbleon** [dashofcode/tracker_api#61]
I would love to see 5xx responses raise a `TrackerApi::TransientError` to let client code handle transient errors (timeouts, etc) differently than permanent errors (auth problems, bad requests, etc). For example, I would like to retry if there is a transient error, but not if there is a permanent error.

`TrackerApi::TransientError` could be a child of `TrackerApi::Error` to preserve compatibility with existing client code.

Here are a few examples of errors our app has reported. I'm assuming that these responses were accompanied by an appropriate 5xx HTTP status code.

```
A TrackerApi::Error occurred in background at 2016-01-20 08:29 :

  757: unexpected token at '<h1>This website is under heavy load</h1><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/client.rb:207:in `rescue in request'
```

```
  A TrackerApi::Error occurred in background at 2016-02-04 07:11 :

  757: unexpected token at '<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

'
  /app/vendor/bundle/ruby/2.2.0/gems/tracker_api-0.2.11/lib/tracker_api/client.rb:207:in `rescue in request'
```

**Comment by forest** [comment]
I think adding this behavior is the right direction. Are you interested in making the updates?

**Comment by sbleon** [comment]
Thanks for the positive feedback, @forest. I’m interested, but I don’t know
if I’m going to have time anytime soon.

**Comment by patientdev** [comment]
Relatedly (hi @sbleon), is there interest in fleshing out `::TrackerApi::Error` to handle specific [Error Responses](https://www.pivotaltracker.com/help/api#Error_Responses) from the Tracker API? I could work on this over the next few weeks.

**Comment by sbleon** [comment]
@patientdev what were you thinking of? Subclasses of `::TrackerApi::Error`
could correspond either to HTTP statuses or to Tracker's `code` field
values. Or we could just have two subclasses (for 4xx "client is wrong" and
5xx "server is broken" error codes), which is the only distinction that I
really care about at the moment. If we started with a
`::TrackerApi::InputError` for 4xx and a `::TrackerApi::ServerError` for
5xx, we could always subclass those further in the future.

**Comment by forest** [comment]
@sbleon That proposal seems good. I'd vote for starting simple and getting more detailed as needed.

**Comment by patientdev** [comment]
👌 Sounds good to me. I'll subclass generic 4xx and 5xx responses to start.
